services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yaml
      service: network-deploy-service
      
  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3307
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yaml
      service: network-deploy-service
      
  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3308
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yaml
      service: network-deploy-service
  
  configserver:
    image: toharifqi/configserver:s6
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on: 
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config 
        
  accounts:
    image: toharifqi/accounts:s6
    container_name: accounts-ms
    ports:
      - "8080:8080"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on: 
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
  
  loans:
    image: toharifqi/loans:s6
    container_name: loans-ms
    ports:
      - "8090:8090"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on: 
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"
          
  cards:
    image: toharifqi/cards:s6
    container_name: cards-ms
    ports:
      - "9000:9000"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on: 
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
  
networks:
  xbank:
    driver: "bridge"
          
